theme: jekyll-theme-cayman
title: Buddy Check â€“ Before the Doom Scroll
description: Helping people reclaim time by interrupting doomscrolling habits.


nav:
  - Home: index.md
  - Team: team.md
  - Presentations: presentations.md
  - Deliverables:
      - Overview: deliverables-overview.md
      - Process Flow: deliverables-process-flow.md
      - MFCD: deliverables-mfcd.md
      - Risk Matrix: deliverables-risk-matrix.md
      - Competition Matrix: deliverables-competition.md
